[package]
name = "ergo-cyti-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
ergotree-ir = "0.20"
ergo-lib = "0.20"
bounded-vec = "0.7.1"
rayon = "1.5"
